### ISSUE TITLE
AppNavigationSettings aren't visible on chromium mobile

### ISSUE THREAD

**Issue by szaimen** [nextcloud/nextcloud-vue#1105]
### Steps to reproduce
1. open tasks app
2. open side menu
3. settings on the buttom aren't visible

### Expected behaviour
they should be visible

### Actual behaviour
they aren't visible

### Server configuration

**Operating system**:
ubuntu 18.04
**Web server:**
apache2
**Database:**
pgsql
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
18.0.4
**Tasks version:** (see Nextcloud apps page)
v0.13.1
**Updated from an older Nextcloud or fresh install:**
updated
**Signing status:**

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
chromium mobile 81 based browser
**Operating system:**
Android 10

### Screenshot
![image](https://user-images.githubusercontent.com/42591237/82664808-d390c700-9c32-11ea-8704-68968989a313.png)

**Comment by raimund-schluessler** [comment]
Are you sure it’s not visible? Have you tried scrolling? It works fine for me on Chrome for iOS, but I cannot test on Android, since I don’t have such a device.

Since we use the vue components for Tasks, I transferred the issue here. Can you please check if you see the settings in other apps using the components such as Calendar or Contacts?

**Comment by szaimen** [comment]
@raimund-schluessler Yes, it isn't visible there and I cannot scroll down in the sidebar;
btw: in firefox mobile 75 beta6 it is visible; in other vue based apps like e.g. calendar it works also on chromium mobile,
So I would guess that it is Tasks app related?

**Comment by raimund-schluessler** [comment]
Tasks is just using the nexcloud-vue `AppNavigationSettings` component, and nothing more: https://github.com/nextcloud/tasks/blob/master/src/App.vue#L26-L28 and the CSS just describes the content of the settings https://github.com/nextcloud/tasks/blob/master/css/src/style.scss#L187-L238. So at least the settings header should be visible and I don't have an idea what could break it. And since I don't own an Android device, I cannot reproduce or debug it. So if anyone would be able to reproduce it at least, that would be great.

**Comment by szaimen** [comment]
Actually it seems like the settings button is visible but only if I close the side menu, scroll down in the tasks list so that the button bar of the browser gets hidden and then open the side menu, the settings button is visible.

So I guess this is because the vue component knows that the button bar on the bottom can be hidden and thus calculates the available space wrong so that it is actually on the very bottom and not visible because of the button bar of my browser?

Does that make sense?

**Comment by raimund-schluessler** [comment]
Now that I think about it, Tasks is one of the first apps to ship nextcloude/vue@2.0.0. The stable version of Calendar is still at 1.5.0, Contacts even 1.4.1. In version 2.0.0 the left sidebar was reworked, so I guess this issue could be due to https://github.com/nextcloud/nextcloud-vue/pull/989.

**Comment by szaimen** [comment]
I think this was fixed in the meantime
