### ISSUE TITLE
User mention in comment field does not work for users with @ in name

### ISSUE THREAD

**Issue by roadrunnerjb** [nextcloud/nextcloud-vue#1825]
First I thougt its solved with NC21. Selction works but we have users with special chars as "@" in their usernames. When I select one of those users the "@" inside the username is removed and so the user mention does not work

_Originally posted by @roadrunnerjb in https://github.com/nextcloud/server/issues/19523#issuecomment-810150432_

**Comment by alex-jensen-wb** [comment]
> First I thougt its solved with NC21. Selction works but we have users with special chars as "@" in their usernames. When I select one of those users the "@" inside the username is removed and so the user mention does not work
> 
> _Originally posted by @roadrunnerjb in [nextcloud/server#19523 (comment)](https://github.com/nextcloud/server/issues/19523#issuecomment-810150432)_

Can we please assign a milestone to get this bug fixed?  Any Nextcloud instance whose users are setup with email addresses as their username's are not currently able to use auto-complete @ mention comments.  When taking other, since resolved, bugs into account, [this appears to have been an issue](https://github.com/nextcloud/server/issues/19523) since 17.
