### ISSUE TITLE
Allow material-design-icons in AppSidebarTabs

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/nextcloud-vue#1859]
Currently, you can only provide a string which is set as a class. It would be nice to allow material-design-icons as we do it e.g. for Actions.

**Comment by skjnldsv** [comment]
Time for the Icon component? :see_no_evil:

**Comment by raimund-schluessler** [comment]
> 
> 
> Time for the Icon component? 🙈

What should it do?

**Comment by skjnldsv** [comment]
We discussed it a bit before, but having a component that would translate a string into an icon with dynamic loading & caching would be quite nice.
It would support IDs like

`mdi:Menu`, `app:contacts` or `mimetype:mp4`, and would have the logic to manage and fetch them.

Because our main issue is that lots of our APIs are also in php (like settings) a,d passing an icon-id via string would solve all of it. No more slots, just a nice universal way of dealing with icons.

One issue was the IE compatibility, but now that we have dropped it, it might be good to dive into this and have a webComponent that can be used in pure js too?
