### ISSUE TITLE
New list item component, action menu mobile use and accessbility

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/nextcloud-vue#2340]
Mail uses the new app content list item component from nc/vue. This looks and works great on desktop, but on mobile there is a little accessibility issue IMO. The issues is that by default we always show the timestamp of the message, on hover (desktop) the actions menu handle shows. There is no hover on mobile, so that menu is a "hidden" feature. You can still click and get a menu, but a user wouldn't know about this.

@nextcloud/designers possibly something to discuss

**Comment by jancborchardt** [comment]
> I think showing the menu for all apps on mobile is okay as a starting point because right now none of them are accessible, and then later we can think about the actions in it and if they are useful.

Yup, sounds good. And then making it look like Marco proposed at https://github.com/nextcloud/nextcloud-vue/issues/2340#issuecomment-951955577 would work.

> In my view we can default with actions on on mobile too in the case of talk, as long as we don't reintroduce them in the main (desktop) web UI

The issue here is that the differentiation is not mobile/desktop, but it’s touch/non-touch, and we can’t reliably differentiate that. People might have a tablet which is as big as some screens (iPad Pro) or they have a laptop with a touchscreen.
