### ISSUE TITLE
why multi select options is spliting?

### ISSUE THREAD

**Issue by mjalili27** [nextcloud/nextcloud-vue#2363]
hi thanks for your great project but i have a problem with persian/arabic language in select opthins.
as you can see in EllipsisedOption the names gets splited. in english it is ok but in persian/arabic or non latin langs it seperates the names.
like: [ No reminder => عدم ی‌ادآور]
it sould be: عدم یادآور
so my question is what is the propose of this spliting?
is it realy needed?
how can be fixed?
![image](https://user-images.githubusercontent.com/31030497/142725644-2d5b84a8-eb17-40e8-9920-50bdd54f139b.png)
![image](https://user-images.githubusercontent.com/31030497/142725698-3c59a207-d78b-4aff-a6ce-4ee89f794997.png)

**Comment by raimund-schluessler** [comment]
The reason why we split the texts is that we want to improve the usability in case of very long option names that would otherwise be ambiguous and difficult to select.

Consider three options like
```js
[
"Very long option only differs at the end 1",
"Very long option only differs at the end 2",
"Very long option only differs at the end 3"
]
```
If we would ellipsis these option at the end, they couldn't be told apart. By splitting in the middle and still showing the end, you can select them just fine:
<img width="164" alt="options" src="https://user-images.githubusercontent.com/2496460/143220466-c01b1eea-92e1-4819-996e-e9f007c0b13d.png">

However, the component should also work with other languages than English. I just don't yet understand the problem. Could you please elaborate a bit on why this is problematic in arabic/persian?

**Comment by raimund-schluessler** [comment]
Since there is no further input as to how it should work for persian/arabic, I will close this issue. Please reopen if you feel to contribute to this question.
