### ISSUE TITLE
Improve the breadcrumbs component

### ISSUE THREAD

**Issue by nimishavijay** [nextcloud/nextcloud-vue#2410]
As discussed with @jancborchardt and @marcoambrosini during the Vue components design review

![breadcrumbs-grey-padding](https://user-images.githubusercontent.com/52440189/146420095-cf4f674c-a270-4cea-9955-609a06b9ec82.gif)

- The right arrow that separates the folders is super thin and sort of disappears into the bg, so it can be replaced by `chevron-right` MDI icon
- We can have a better hover feedback, where the background colour is `#ededed` (`--color-background-dark` ?) and text is `--color-main-text`
- Also used `home` MDI icon here 

also cc @skjnldsv for Files

**Comment by marcoambrosini** [comment]
Looks good. One tiny detail: I would loose the last chevron icon to the right since the new button is sort of in the same context of the current folder

**Comment by raimund-schluessler** [comment]
I can take care of this. I am just happy you don't want any drastic functional changes (yet), since this component is quite complex 😄.
The home icon is already configurable since the single breadcrumb has a slot for an MD icon. So it is possible to set the correct icon already. However, if the breadcrumb has no icon slot set and you don't specify a `rootIcon`, it falls back to `icon-home` which is a standard (non-MD) icon coming from server:
https://github.com/nextcloud/nextcloud-vue/blob/987b0b1d1ded90059f0926534f0cdbc4442444ef/src/components/Breadcrumbs/Breadcrumbs.vue#L119-L122

So I have a couple of questions:
- Do you want me to change the home icon to MDI `home` by default if no `rootIcon` is given?
- Do we even need to still allow setting icons by string, or can we completely move to MDI icons only and remove the `rootIcon` and corresponding `icon` string prop? This would make it a breaking change, but I think that is not critical, since the component is not yet used in any official Nextcloud app. Plus we would then really enforce MD icons.
- You don't mention the rounded corners of the hover feedback, but show it in the video. I suppose you want them?
- Is the arrow down of the last breadcrumb desired? If so, should we use
`menu-down`: 
![Screenshot 2021-12-20 at 11-33-36 Material Design Icons](https://user-images.githubusercontent.com/2496460/146753652-4ab233d0-b2aa-4044-a73e-195bfb180c1c.png)
or `chevron-down`: 
![Screenshot 2021-12-20 at 11-33-30 Material Design Icons](https://user-images.githubusercontent.com/2496460/146753677-5bba622a-1156-4161-848e-73cbe3c3b7dc.png)

**Comment by raimund-schluessler** [comment]
> Will be in 24. So I'm fine using a slot if needed. But we need to make sure we have this soon so we don't break it mid-schedule :)

If you only use the icon slot and not the icon prop (as anyway required for MD icons), there won't be any problem if we remove the icon prop. Anyway, I will have a look soon.

**Comment by raimund-schluessler** [comment]
I just saw we also need to show an MD icon by default for the hidden breadcrumbs in the dropdown at
https://github.com/nextcloud/nextcloud-vue/blob/987b0b1d1ded90059f0926534f0cdbc4442444ef/src/components/Breadcrumbs/Breadcrumbs.vue#L500
We currently just show `icon-folder` from server.

I will also check if it might also be possible to kind of forward the breadcrumb icon slot to the ActionButton icon slot, in case the breadcrumb is hidden.

**Comment by raimund-schluessler** [comment]
The first step is in #2411.

**Comment by raimund-schluessler** [comment]
Todo:
- [ ] Use `ChevronRight` as separator #2411 
- [ ] Show rounded background on hover #2411
- [ ] Show `MenuDown` for last breadcrumb
- [ ] Fall back to MD icon `home` as root icon if not specified differently
- [ ] Use MD icon `Folder` as fallback in hidden crumbs dropdown
- [ ] Use provided brumb icons in hidden crumbs dropdown

**Comment by nimishavijay** [comment]
> Do you want me to change the home icon to MDI home by default if no rootIcon is given?

Yes, since we're moving towards standardising MDI this would be a good idea

> You don't mention the rounded corners of the hover feedback, but show it in the video. I suppose you want them?

Haha, yes! Looks great in #2411!

> Is the arrow down of the last breadcrumb desired? 

Yeah, so ideally we were thinking of having an action menu there next to the current folder instead of a share icon, so on clicking the arrow the action menu would appear.
I like the idea of using `chevron-down` but I tried it out and it looks a little bit confusing as it's too similar to `chevron-right` 
![image](https://user-images.githubusercontent.com/52440189/146940272-35fa15f8-be32-432d-b68a-8a800564c3b0.png)

I'd say we can go with `menu-down` here

**Comment by raimund-schluessler** [comment]
> Yeah, so ideally we were thinking of having an action menu there next to the current folder instead of a share icon, so on clicking it the action menu for the folder would appear.

This can be done already. If you supply e.g. multiple `ActionButton` they are rendered in an `Actions` dropdown with a three-dots menu. I guess we just need to create a slot allowing to customize the trigger icon so that we can throw in `MenuDown` instead of the three-dots for example.

**Comment by raimund-schluessler** [comment]
Reopening, since we are not done yet :slightly_smiling_face:

**Comment by quentinguidee** [comment]
Happy to see improvement on the breadcrumbs! The only issue I see here is about the paddings. Currently, because the button have a big height, the circles visually (in mind) cut the text and one has the impression of being tight. Currently :

![before](https://user-images.githubusercontent.com/12123721/146992199-9ecb1ea5-14a6-4083-aaee-f72010d8710d.png)
![before-layout](https://user-images.githubusercontent.com/12123721/146992212-655f2457-92b6-4495-957a-54e3ed529ffa.png)

Would be better in my opinion to have something like this :

![concept](https://user-images.githubusercontent.com/12123721/146992257-1018df9c-6d02-4364-92f1-83f1896e6401.png)
![concept-layout](https://user-images.githubusercontent.com/12123721/146992368-04391ee9-9a2c-43e7-b806-a5f7b178169d.png)

Principle also found in material design guidelines on this big round buttons :
![Capture d’écran 2021-12-21 à 09 51 20](https://user-images.githubusercontent.com/12123721/146993405-3d3d1045-5fc9-4da1-9a52-73bc943ebd86.png)
![Capture d’écran 2021-12-21 à 09 51 20 copie](https://user-images.githubusercontent.com/12123721/146993381-b2e04a55-2af6-40a7-8c3d-b49a1a061154.png)

Or on smaller buttons (also material design, or with Nextcloud) :
![md](https://user-images.githubusercontent.com/12123721/146993494-298b5a1c-a60b-4663-9bd2-c8859fb984b9.png)
![Capture d’écran 2021-12-21 à 21 08 07](https://user-images.githubusercontent.com/12123721/146993506-45d154ae-ca8a-46cc-987b-fd3a16c645d5.png)

**Comment by raimund-schluessler** [comment]
> Would be better in my opinion to have something like this :
> 
> ![concept](https://user-images.githubusercontent.com/12123721/146992257-1018df9c-6d02-4364-92f1-83f1896e6401.png) ![concept-layout](https://user-images.githubusercontent.com/12123721/146992368-04391ee9-9a2c-43e7-b806-a5f7b178169d.png)

I agree that it looks better for the single (hovered) breadcrumb. The crumbs are 44 px high, which means we need 22 px left/right padding to achieve what you propose (border radius ends at the position of the text). The problem is that if we do that and you don't hover over a breadcrumb, I think there is to much space. And we can show less breadcrumbs, obviously.

See:
![Screenshot 2021-12-21 at 21-39-38 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/146995046-6a003c0b-80fc-4659-b5ee-90c8d5b00f67.png)
![Screenshot 2021-12-21 at 21-39-46 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/146995055-784ecd90-6d20-450e-b835-d3567dd63c09.png)

**Comment by quentinguidee** [comment]
Yes, I realized the problem while doing it in devtools. But I think the problem is viewed from the wrong angle here. If the *necessary* horizontal margins are too large, then it's because the button is too high. Even if the "bug" is only visible when you pass over it, it remains an unpleasant visual bug for the end user. I don't think prioritizing maximum size goes over a nice interface (just as a nice interface doesn't go over functionality, the two should be judged equally).

**Comment by quentinguidee** [comment]
And for info Google Drive uses a 32px height breadcrumbs, so I don't think a button that high is necessary in this context.

**Comment by raimund-schluessler** [comment]
> If the _necessary_ horizontal margins are too large, then it's because the button is too high.

I also thought about that and it would really solve or at least reduce the problem. But I don't know if that is desired here, since the general rule all over Nextcloud is that any clickable element should be at least 44 px times 44 px to make it accessible by touch as well. Reducing the height to e.g. 32 px would violate this principle.

**Comment by quentinguidee** [comment]
Ok, thanks! Didn't know that it should be accessible by touch by default. But then what about this button (32px too) ? 
![Capture d’écran 2021-12-21 à 21 08 07](https://user-images.githubusercontent.com/12123721/146993506-45d154ae-ca8a-46cc-987b-fd3a16c645d5.png)

Seems totally usable by touch, or maybe an intermediate size would be ideal, like 38px ?

![Capture d’écran 2021-12-21 à 22 19 53](https://user-images.githubusercontent.com/12123721/146999229-a5fa4c07-b84d-41ed-bf98-6a9b15c8b001.png)

I think that even in mobile apps the buttons are not that high : 
![image](https://user-images.githubusercontent.com/12123721/146999717-2e4df5c7-1cda-4ce8-b92f-ae0e095e2a3e.png)

**Comment by raimund-schluessler** [comment]
> Ok, thanks! Didn't know that it should be accessible by touch by default. But then what about this button from NextCloud (32px too) ? ![Capture d’écran 2021-12-21 à 21 08 07](https://user-images.githubusercontent.com/12123721/146993506-45d154ae-ca8a-46cc-987b-fd3a16c645d5.png)

Yeah, I am afraid Nextcloud is not totally adhering to these rules everywhere yet. That's also why we now e.g. have a button component in nextcloud/vue so it looks the same everywhere (once it's used everywhere :see_no_evil:).

But this discussion is more for @jancborchardt and @nimishavijay, since they do the Nextcloud design :wink:

**Comment by quentinguidee** [comment]
Ok, thanks for your comments! 👍 

For illustration purpose, here's what a 38px button would look like

![image](https://user-images.githubusercontent.com/12123721/147001500-b753618c-a490-4f85-b421-4473009b048d.png)

Or a 40px height :

![image](https://user-images.githubusercontent.com/12123721/147001606-fae4e930-2d44-40e5-974b-75ecad9d393b.png)

**Comment by raimund-schluessler** [comment]
Another option would be to use the `border-radius: 16 px;` from the `AppNavigationItem`. Together with 16 px left/right padding it looks like this (still a bit much white-space, but much less than 22 px would create):
![breadcrumb](https://user-images.githubusercontent.com/2496460/147059803-de415724-b6eb-4381-a257-d2f5e025fa51.gif)

I think this could even make sense, since it creates a relation to the `AppNavigationItem`s which will be used in the new Files app. Both elements are for navigating and will bring you to another view, rather than merely triggering an Action on the same site as a button would.

But I think this is enough input for @nextcloud/designers now. Your call. 🙂

**Comment by marcoambrosini** [comment]
@raimund-schluessler I think that works!
