### ISSUE TITLE
Add option to create new element in <SettingsSection> header

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/nextcloud-vue#2515]
The Talk admin settings (maybe some other apps settings ?) makes use of this for instance.

![image](https://user-images.githubusercontent.com/2197836/155177734-074c6ed3-e9df-4dca-bddf-cea148bfe4bc.png)

Is this a pattern that should be encouraged, or should there just be a regular button on top of the content list (or in an `<EmptyContent>` component) ? @nextcloud/designers  

If so, is the way it's implemented in Talk settings the correct way, especially on accessibility levels (a link instead of a button, itself in the `<h2>`)?
```vue
<h2>
  {{ t('spreed', 'STUN servers') }}
  <span v-if="saved" class="icon icon-checkmark-color" :title="t('spreed', 'Saved')" />
  <a v-else-if="!loading"
    v-tooltip.auto="t('spreed', 'Add a new server')"
    class="icon icon-add"
    @click="newServer">
      <span class="hidden-visually">{{ t('spreed', 'Add a new server') }}</span>
    </a>
  <span v-else class="icon icon-loading-small" />
</h2>
```

I'm asking before I start implementing this in [`<SettingsSection>`](https://nextcloud-vue-components.netlify.app/#/Components/Settings?id=settingssection) (kinda like how the link to docs works)

**Comment by jancborchardt** [comment]
The only icon/action we should show next to a title is a possible link to the documentation, as e.g. in Sharing here:
![image](https://user-images.githubusercontent.com/925062/155532473-484a1e70-c2fc-4d9b-a489-e1056a8c1d4b.png)

An "add new entry" action like here is better placed at the end of the list, where the new entry would also appear. (One reason is that otherwise the "Add new entry" buttons are not in a consistent place cause the heading text is of different lengths.) cc @nickvergessen for Talk admin settings on that.

**Comment by nickvergessen** [comment]
Yeah the settings have not been adjusted to recent patterns for a long time as we are busy with actual talk UI.

**Comment by tcitworld** [comment]
Thanks for the reply!

**Comment by jancborchardt** [comment]
@tcitworld we could however think about standardizing that "Open documentation" action?

**Comment by tcitworld** [comment]
This is already there in `<SettingSection>` as the `doc-url` prop.
https://nextcloud-vue-components.netlify.app/#/Components/Settings?id=settingssection
