### ISSUE TITLE
Left sidebar handle missing when loading page in mobile view

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/nextcloud-vue#2537]
When the screen is in a small size so the left sidebar is not displayed by default, the toggle for it is there but there is no icon shown:
![Peek 2022-03-07 11-02](https://user-images.githubusercontent.com/213943/157009973-fb00a729-21c7-41d0-87e1-cab5c4b163d4.gif)

**Comment by dartcafe** [comment]
@nickvergessen Thanks. I noticed this too and thought, I produced this issue in polls and had it on my to do list. 😆

**Comment by juliushaertl** [comment]
Might also be a case where https://github.com/nextcloud/nextcloud-vue/pull/2532 could help with a single action. Might be worth trying with master of `@nextcloud/vue`

**Comment by mejo-** [comment]
We have the same issue in the current Collectives release (with nextcloud-vue 5.0.0). In our main development branch we upgraded to nextcloud-vue 5.2.1 some time ago and there I'm unable to reproduce the issue. So I'm pretty sure that it got fixed by #2532.

@nickvergessen did you find time to test with latest nextcloud-vue?

**Comment by nickvergessen** [comment]
Seems fixed with 5.3.0+
