### ISSUE TITLE
ActionCaption does not work if it is the only child of Actions

### ISSUE THREAD

**Issue by susnux** [nextcloud/nextcloud-vue#2789]
If `Actions` only contain one or more `ActionCaption` the Actions can not be triggered.

This should probably work as there is an example doing exactly this [see documentation example](https://nextcloud-vue-components.netlify.app/#/Components/Actions?id=actioncaption).
But this example does not work for me (if relevant: I use Firefox version 101)

My use case: Using it within an overflow menu (if screen size shrinks more entries are added), but it could be empty and only contain the caption (which shows some information and is always a child of the `Actions`).

**Comment by raimund-schluessler** [comment]
The example shows two captions, and works as expected for me:
![Screenshot 2022-08-07 at 22-12-02 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/183309365-25044a03-a421-4782-9a0f-aff5390fb7bd.png)

 However, if you really only have one entry (i.e. one ActionCaption in this case) the Actions component falls back to a single button without a dropdown menu, and, since it only contains a caption, shows nothing.

If you want it to show a single caption in a dropdown menu, you need to add `forceMenu="true"` to the `Actions` component, like so:
```vue
<Actions forceMenu>
	<ActionCaption title="Test caption" />
</Actions>
```
![Screenshot 2022-08-07 at 22-13-08 Nextcloud Vue Style Guide](https://user-images.githubusercontent.com/2496460/183309399-c37bfb9c-7b10-44f1-9253-2850f1e58541.png)

@susnux I think this is the proper and expected behaviour. Please speak-up / reopen if you disagree.
