### ISSUE TITLE
Design improvements & issues in ListItem

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud-vue#2853]
Based on the Mail app, here are some proposed design improvements and issues in AppContentListItem:
- [x] There is no whitespace left and right of the element. E.g. 4px whitespace would make it look much better, like we do for the updated AppNavigation: https://github.com/nextcloud/nextcloud-vue/pull/2571#issuecomment-1142641888
- [x] For improved focus, we could always bold the main text, in this case the sender. Then we could also put the subline in color-main-text, and only bold the subline on unread. (The unread bubble indicator is also there like in Talk, so that is plenty indication.)

@marcoambrosini @GretaD what do you think?

→ Issues specific to Mail filed at https://github.com/nextcloud/mail/issues/6901

![Mail navigation](https://user-images.githubusercontent.com/925062/179492565-a390d557-caa0-4253-a209-994efdbc296d.png)

**Comment by jancborchardt** [comment]
Ref also https://github.com/nextcloud/mail/issues/6079 by @nimishavijay which has a complete mockup of it.

**Comment by marcoambrosini** [comment]
Whitespace: I'd refrain from adding margin to these components, given that they can be used in different contexts. I'd add some padding left and right to the parent component instead (`AppNavigation` or `AppContentList`), since we don't want anything at all to touch those edges anyway.

Focus behaviour: changing the font weight on focus will result in words jumping around and being ellipsized at different lengths depending on the focus state. I think we should implement something similar to the button component instead:

https://user-images.githubusercontent.com/26852655/179524927-49404da1-31a0-4ccc-a08f-1f04cf78f58b.mov

Another comment here for the groupware team since this is assigned to them. You can see that the content of the list item is not vertically centred with its background, I suspect you're populating the slot for the tags with something even when there are no tags.

**Comment by nimishavijay** [comment]
>  For improved focus, we could always bold the main text, in this case the sender.

Bolding is used as a read/unread indicator in some apps, so should take that into consideration.
Agreed about the whitespace ✓

**Comment by marcoambrosini** [comment]
oh ok, sgtm too then :)

**Comment by jancborchardt** [comment]
These points have been fixed meanwhile! :)
