### ISSUE TITLE
Button too big

### ISSUE THREAD

**Issue by jotoeri** [nextcloud/nextcloud-vue#2906]
As the Button-Component uses the box-shadow to create the border it is effectively 48px large. The `border-box` seems not to respect the shadow. Comparing the AppNavigationNew to the old version, the new Button feels like a monster.

As i didn't fully understand, why the shadow is used, this as an issue (instead of PR):

How can we reduce the size of the button component, so it really is 44px in height? Changing from shadow to border? Or reducing the button height to 40px, so it is effectively 44px with shadow? @marcoambrosini @jancborchardt ?

**Comment by jancborchardt** [comment]
Sounds sensible – the element itself (incl border) should be 44px high, not 48. I also assume this is not intentional since you were always worried about the size of buttons @marcoambrosini? :)

**Comment by raimund-schluessler** [comment]
The button really looks bigger than it actually is, due to
https://github.com/nextcloud/nextcloud-vue/blob/6e788124bafa8dd0dbb08cb1fc9ec29baba9109b/src/components/Button/Button.vue#L603
for example. In this image, the button is directly adjacent to the hovered dashboard entry, and does not actually overlap, but the `box-shadow` makes it look like it does:
![Screenshot 2022-08-01 at 21-48-24 Dashboard - Nextcloud](https://user-images.githubusercontent.com/2496460/182233480-92168b63-5c41-452b-87fb-9a07ba5ebf8c.png)

**Comment by jotoeri** [comment]
Yes, so it seems to be mainly a problem of the secondary button. That one uses shadow-border not only for focus feedback, but also for its regular outline, which then results in the 48px.
I think the main border of the button should be moved to the border-property, so it is within the 44px height. Then just the question remains, how to handle that focus-border? Just changing the new inner borders color as currently done? Or keeping an additional shadow, effectively producing two borders? :thinking:

**Comment by marcoambrosini** [comment]
Ok, I misunderstood. I thought you were referring to the focus feedback
