### ISSUE TITLE
NC25: All the conversations are in bold in the left panel, no matter if they contain unread messages

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/nextcloud-vue#3293]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Steps to reproduce
Open the Talk Web UI and check the conversations list

### Expected behaviour
In Nextcloud 24 the conversations listed in the left panel in bold are those with new messages. This behaviour should be the same in Nextcloud 25.

### Actual behaviour
In Nextcloud 25 (version installed on c.nc.com) all the conversation are in bold, no matter if they contain unread messages. I think this is confusing for the user.

## Talk app

c.nc.com

### Browser log

</details>

## Server configuration

c.nc.com

**Comment by nickvergessen** [comment]
This is because with the latest design decision it was chosen to make all titles bold in the app navigation.

I also agree that it heavily impacts the usability of the conversation list, so maybe it can be reconsidered?
We also got a lot of internal comments regarding this.

cc @jancborchardt @nimishavijay

**Comment by jancborchardt** [comment]
So I am also not entirely sure about this. But I also think this might just be historical for us. In many popular applications (like Apple Mail, Discord, WhatsApp), bolding is used to give structure, _not_ an indicator for something being unread, cause they have actual indicators for that (like we have now).

Unread messages directly to you have, in both Mail and Talk, a prominent blue indicator on the right, just like e.g. Apple Mail.

What do you think @marcoambrosini @nimishavijay?

**Comment by nickvergessen** [comment]
> In many popular applications (like Apple Mail, Discord, WhatsApp), bolding is used to give structure, not an indicator for something being unread

Just for the record, Thunderbird does use bold for subjects of unread emails and folders with unread emails.

**Comment by marcoambrosini** [comment]
this is a deliberate decision @pmarini-nc and although I didn't quite agree at the beginning I kind of like it now because of the structure that it gives to the list, as @jancborchardt mentions. That said, I don't have strong feelings about this and I'm fine either way.
One thing that becomes very apparent now though is that our counters are not visible enough, especially the regular and the team mention ones

> Just for the record, Thunderbird does use bold for subjects of unread emails and folders with unread emails.

This strategy seems to have been dropped in the new UI they're about to launch

**Comment by PVince81** [comment]
it seems that the boldening situation has improved in the latest releases
at least it doesn't disturb me as much as it used to

close ?

**Comment by mejo-** [comment]
Given that @PVince81 asked for the issue to be closed on Nov 4th and @pmarini-nc (the original author) reacted with thumbs up, I'll close the issue. Feel free to reopen if you disagree.
