### ISSUE TITLE
Missing dependencies on node modules

### ISSUE THREAD

**Issue by hschletz** [nextcloud/nextcloud-vue#3696]
After upgrading to 7.x, webpack build failed with several messages like:
````
Module not found: Error: Can't resolve 'assert' in '[...]/node_modules/@nextcloud/vue/dist'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.
````
Same for the "buffer" and "util" modules. As a workaround, I added those packages to my project:

`npm install assert buffer util`

The commonly suggested fallback configuration was not necessary.

Shouldn't these dependencies be handled by the nextcloud-vue package?

**Comment by ChristophWurst** [comment]
Found the same issue with https://github.com/nextcloud/mail/pull/7954

**Comment by raimund-schluessler** [comment]
I was wondering why my apps were not affected, but it's probably because they use [@nextcloud/webpack-vue-config](https://github.com/nextcloud/webpack-vue-config) which brings a peer dependency to `node-polyfill-webpack-plugin`. Maybe we should add this peer dependency to `@nextcloud/vue` as well, so it also works without using `@nextcloud/webpack-vue-config` (although it's not a bad thing to use the shared webpack config 😉).

**Comment by ChristophWurst** [comment]
If this lib has a peer it expects then it should been in package.json :+1:
