### ISSUE TITLE
[BITV] Buttons accessibility improvements

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/nextcloud-vue#4193]
Update: I hid the previous conversation as we were going in the wrong direction. I'm updating the description with the specific accessibility problems that we have in the button component as per the call with the expert last week.  

To be addressed:

- [x] Focus state: currently there's not enough contrast between the background of the buttons and the dark outline we have. 
Solution: Add 2 outlines as focus state to buttons, both 2px thick. The inner should be `--color-main-text`, and the outer `--color-main-background`

<img width="811" alt="Screenshot 2023-06-30 at 11 12 46" src="https://github.com/nextcloud/nextcloud-vue/assets/26852655/fdcb465c-a3a9-4c50-9f11-d62dda7217ee">

- [x] Primary button hover state doesn't meet text contrast requirements (needs solution)
- [x] Special buttons don't meet text contrast requirements (needs solution)

**Comment by marcoambrosini** [comment]
Why exactly do we need that @jancborchardt  @JuliaKirschenheuter ?  What would be the color of the text and of the outline?

**Comment by nimishavijay** [comment]
@marcoambrosini the current style of the secondary button doesn't have enough contrast with the background, so it wouldn't meet a11y requirements.

For colors I think we could keep it similar to the screenshot, `--color-primary-element` text (in bold font) and `--color-border-maxcontrast` outline? it would look something like this:

![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/f608e499-2b67-4132-b2af-2e63c0d094c7)

The bold text and rounded corners are what differentiate it from an input field. What do you think?

**Comment by marcoambrosini** [comment]
@nimishavijay or @JuliaKirschenheuter could you point me to the accessibility requirements that the secondary button is violating?

**Comment by JuliaKirschenheuter** [comment]
Hi @marcoambrosini, 

> I've done some digging and there seems to be no requirement for button background contrast with the page background.
Here is one example: 

![Screenshot from 2023-06-16 15-27-41](https://github.com/nextcloud/nextcloud-vue/assets/6078378/0be57dfe-8d93-470c-8a9c-19e57892bce4)
https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html

well, it is important that component background have enough contrast with adjacent color outside the component. As well as button text with component background.
But i can't say i've completely understood all this examples and because of it we would like to have a meeting with Michael.

Here was a last state: https://github.com/nextcloud/text/issues/3860#issuecomment-1590774920
All buttons Primary, Secondary and Tertiary and all states of them: Normal, Disabled, Focus and Hover have to meet a11y requirements.

@marcoambrosini @nimishavijay could you please research around all our use cases that we will have a collection of examples which we will discuss? Thank you!

**Comment by marcoambrosini** [comment]
> well, it is important that component background have enough contrast with adjacent color outside the component. As well as button text with component background.

I just can't square in my head how it's ok for the background to be transparent (like in the case of a tertiary button), and at the same time the secondary button is not ok. 

> https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast.html

And I can't find anything here that would require us to give up our secondary button. The only background contrast requirements I see are for active elements.

<img width="961" alt="Screenshot 2023-06-19 at 14 32 44" src="https://github.com/nextcloud/nextcloud-vue/assets/26852655/303e9320-0019-4373-a27c-4fd08fc1f3d4">

That said, buttons don't strictly need and **active (as in pressed) state**. For a **selected state**, why don't we just switch from secondary (or tertiary) to primary? 
@juliushaertl what do you think? Wouldn't this work in the case of text?

**Comment by marcoambrosini** [comment]
So here's a summary of the call:

**Things that don't satisfy contrast requirements:**
- Focus state in primary buttons is not ok. Add inner white focus outline for all buttons to fix.
- Primary button hover state doesn't meed text contrast requirements
- Special buttons don't meet text contrast requirements

**Suggestions:** 
- Try to use buttons with icons as much as possible 
- No outlined buttons not to mix with keyboard navigation states

**Comment by jancborchardt** [comment]
> Try to use buttons with icons as much as possible

@marcoambrosini what is this suggestion based on? And it means "buttons with icons supporting the text", right? :)

**Comment by AndyScherzinger** [comment]
@jancborchardt so to clarify this for me: we only use (2) and (5) from the material button screenshot in the initial description?

**Comment by marcoambrosini** [comment]
@AndyScherzinger we keep using (3) too, and we should give priority to (3) over (5). Reason being that (5) can be more easily confused with a link. This is what emerged from the call. 

We should definitely keep (5) (tertiary) too because they're very useful in control bars like in the case of text, when buttons with backgrounds lined up would overwhelm the UI.
To address the possible confusion with a link, I think we should limit the use of (5)to `icon-only` and `text + icon` buttons, never just `text` buttons. 
@nextcloud/designers maybe we should write clear usage guidelines for buttons?

**Comment by JuliaKirschenheuter** [comment]
> Add inner white focus outline for all buttons to fix

Could be `outline-offset: 2px;` a possible solution? 
As example: 
![Screenshot from 2023-06-21 08-56-36](https://github.com/nextcloud/nextcloud-vue/assets/6078378/3ea69939-8968-443f-b56d-5d9d1f185beb)

**Comment by JuliaKirschenheuter** [comment]
> So here's a summary of the call:

Addition:

- we should make more difference between buttons and links for tertiary buttons (right now it is not possible to differentiate between them).
- hover state: component's background contrast is not important for adjacent background. Only component text have to meet contrast ratio with component's background. 
- normal state for input fields have to met contrast ratio for adjacent background if input field have no text / placeholder inside.
- disabled colors are not important.
- radio button's normal state (as well as every interactive element) have to have more contrast ratio:
![Screenshot from 2023-06-20 08-53-41](https://github.com/nextcloud/nextcloud-vue/assets/6078378/0fba5505-9978-422b-8190-b6d04387c668)

**Comment by JuliaKirschenheuter** [comment]
> To address the possible confusion with a link, I think we should limit the use of (5)to `icon-only` and `text + icon` buttons, never just `text` buttons.

Why not to underline for links? It is very common and accessible way

![Screenshot from 2023-06-21 10-14-45](https://github.com/nextcloud/nextcloud-vue/assets/6078378/ff1d63d7-78a8-46c2-993a-00f7608bd3db)

**Comment by marcoambrosini** [comment]
@JuliaKirschenheuter let's keep the focus of this issue on the buttons. As they told us in the call the links "confusion" is not an accessibility issue. We can open another discussion for that if indeed we think that that's a problem. Many links, for example navigation entries, would look pretty bad if they had a vanilla link style such as underline.

**Comment by JuliaKirschenheuter** [comment]
>  Focus state: currently there's not enough contrast between the background of the buttons and the dark outline we have.
Solution: Add 2 outlines as focus state to buttons, both 2px thick. The inner should be --color-main-background, and the outer --color-main-text

@jancborchardt , @marcoambrosini, @nimishavijay have i understood correct that each type of our buttons should have 2 outlines (primary, secondary, tertiary)?

**Comment by JuliaKirschenheuter** [comment]
I'm afraid we have some problems with secondary button in dark mode ;(

![Screenshot from 2023-06-29 16-59-59](https://github.com/nextcloud/nextcloud-vue/assets/6078378/4ba2df38-cf7f-46a7-9c8e-7222d67d6a3f)

**Comment by nimishavijay** [comment]
@JuliaKirschenheuter the issue with the secondary button in dark mode arises only because of the light coloured image in the background. For most situations the outline combination suggested would work (outer outline with `--color-main-text` and inner outline with `--color-main-background`). 

We also talked about using a single outline with an outline offset, and that would create the same effect visually. But the same issue arises for dark mode secondary buttons on light coloured images. 

I tried all the combinations of using outline and offset, as well as 2 outlines (I used 2 `box-shadow` properties and it works). Using `--color-main-text` for the inner outline and `--color-main-background` for the outer outline seems to works for all cases of the secondary button. Therefore I suggest that for secondary button we use this outline logic. What do you think @JuliaKirschenheuter @marcoambrosini @jancborchardt 

|  | Button in plain background (light mode) | Button in contrasting image background (light mode) | Button in plain background (dark mode) | Button in contrasting image background (dark mode) |
| --- | --- | --- | --- | --- |
| `--color-main-bg` outline + offset | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/39306c62-fcae-4652-821e-1f70e848e6f2) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/ef9b8c25-6acd-4110-8c34-04fcbfec61bc) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/5bb699f6-4a3e-463b-b7e1-b87b110a8e5c) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/e0d4b259-77ee-4ee8-adaa-d5d096f905e5) |
| `--color-main-text` outline + offset | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/7a6ca29f-8e16-4bc5-a5e1-ec99bf422d5a) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/8dbd72d4-f9b8-4b44-a1e0-ebbf633b04d3) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/b1203bc4-9647-4067-a237-1b864d5e4ace) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/0974a71a-97cf-49e6-9330-e3b97f00c53d) |
| `--color-main-text` inner + `--color-main-bg` outer 🥇 | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/e7ab41e7-0e97-499b-b02e-6e1d04765e56) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/5a030f69-6f9e-4f7c-8237-435fcd9403e9) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/74af8801-9dbe-48e1-9f73-e0e8cdc4c9e5) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/7ee0e00a-8194-4764-ac81-df1c8c8bc381) |
| `--color-main-bg` inner + `--color-main-text` outer | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/5ca3c565-313a-45e2-ae36-950158dae74a) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/cf0f6955-a69a-48ac-880b-caf9c529b27e) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/c1824d22-3db3-4678-a549-590af1e04aa3) | ![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/06067079-948b-4db3-aa3a-2018629e91e3) |

**Comment by marcoambrosini** [comment]
@nimishavijay changed the description so it reflects this

**Comment by JuliaKirschenheuter** [comment]
Thanks @nimishavijay a lot for this summary! Agree with your choice, will implement all our buttons (primary, secondary, tertiary) this way.

**Comment by nimishavijay** [comment]
@marcoambrosini for the primary button the contrast requirement seems to work? What needs to be changed here? 

![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/cb6d62a1-ded8-4100-9feb-f227ae3a7465)


As for the special buttons, simply changing the bg color of the button to an accessible color results in this. What do you think? IMHO it's a bit too strong, and the warning color doesn't make much sense when darkened.

![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/1cc80491-1373-448e-8305-311fb628572f)

Another solution is to change it to the style of the secondary buttons, so using a light coloured background and very dark text in light mode, and a dark background and light text in dark mode. I took the original colours and increased the lightness for the background and decreased it for the text until the contrast was sufficient (7.0:1 for success and error, 4.5:1 for warning, does that work?)

![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/ba277045-836e-4d96-ada8-121d2c61de3c)

Advantages of this is that it fits the design language that we have, since the secondary button is used in many places. But a disadvantage is that it is not eye catching enough, especially for dangerous actions like delete. We can also urge devs to always use icons that indicate the type of action. What do you think?

**Comment by marcoambrosini** [comment]
@nimishavijay it's the hover state of the primary button, when the button is lighted by the hover state: the contrast is not sufficient.

As per the special ones as you say I think they're not catchy enough. I would still prefer going with option 1. Can we maybe just drop the `warning` color? I'm thinking that in many places we effectively use the `error` color as a warning.

**Comment by nimishavijay** [comment]
>  it's the hover state of the primary button, when the button is lighted by the hover state: the contrast is not sufficient.

Ah my bad, sorry! the screenshot I attached is was one of the suggestions for a new hover color. You're right the current hover color is too light.

I'm not sure about making it a darker color than `--color-primary-element` because right now we have a nice logic for the hover behaviour, in light mode it is lighter and in darker mode it is darker. 
How about something like `#2C7CAE`. It is very slightly darker than the original hover color and meets the a11y requirement, what do you think? I've pasted a screenshot (the colors look messed up, but there's not much difference in the 2 button colors), left button is current colors and right button is `#2C7CAE` hover.

https://github.com/nextcloud/nextcloud-vue/assets/52440189/03436558-358a-4076-a09f-a2af1ee5e624

![image](https://github.com/nextcloud/nextcloud-vue/assets/52440189/6c815861-980f-4505-9b7a-6447b0e03eae)

**Comment by marcoambrosini** [comment]
> How about something like #2C7CAE.

Looks good to me. Hover feedback is not that important anyway since there's the cursor change

**Comment by JuliaKirschenheuter** [comment]
@nimishavijay, @marcoambrosini 
> Looks good to me. Hover feedback is not that important anyway since there's the cursor change

If i understood it correct then we could stay with hover state on primary button as it currently is, because yes, there is a cursor change. Should we still change something?

**Comment by JuliaKirschenheuter** [comment]
@nimishavijay 
> As for the special buttons, simply changing the bg color of the button to an accessible color results in this. What do you think?

Could you please write new color codes here? Thank you!

**Comment by nimishavijay** [comment]
> If i understood it correct then we could stay with hover state on primary button as it currently is, because yes, there is a cursor change. Should we still change something?

The hover state of the primary button can be changed to `#2C7CAE` which is very similar to the current color but meets the accessibility requirements :)

> Could you please write new color codes here? Thank you!

We are still not sure about this as the color for the warning button isn't ideal? @nextcloud/designers what do you think?

**Comment by JuliaKirschenheuter** [comment]
@nimishavijay thanks a lot!

Could we open another issue regarding spacial buttons please? Because initial issue was only about focus state on our buttons and it seems to be done.

**Comment by jancborchardt** [comment]
@JuliaKirschenheuter special buttons issue opened by @nimishavijay at https://github.com/nextcloud/nextcloud-vue/issues/4324 – can this be closed then?

**Comment by JuliaKirschenheuter** [comment]
> can this be closed then?

should be merged and then i will close it ;)
